# coding: utf-8

"""
    BloxOne Anycast API

    Anycast capability enables HA (High Availability) configuration of BloxOne applications that run on equipment located on customer's premises (on-prem hosts). Anycast supports DNS, as well as DNS-forwarding services.  Anycast-enabled application setups use multiple on-premises installations for one particular application type. Multiple application instances are configured to use the same endpoint address. Anycast capability is collocated with such application instance, monitoring the local application instance and advertising to the upstream router (a customer equipment) a per-instance, local route to the common application endpoint address, as long as the local application instance is available. Depending on the type of the upstream router, the customer may configure local route advertisement via either BGP (Boarder Gateway Protocol) or OSPF (Open Shortest Path First) routing protocols. Both protocols may be enabled as well. Multiple routes to the common application service address provide redundancy without the need to reconfigure application clients.  Should an application instance become unavailable, the local route advertisements stop, resulting in withdrawal of the route (in the upstream router) to the application instance that has gone out of service and ensuring that subsequent application requests thus get routed to the remaining available application instances.  

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from anycast.models.ospf_config import OspfConfig


class TestOspfConfig(unittest.TestCase):
    """OspfConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OspfConfig:
        """Test OspfConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OspfConfig`
        """
        model = OspfConfig()
        if include_optional:
            return OspfConfig(
                area = '0.0.0.1',
                area_type = '',
                authentication_key = '',
                authentication_key_id = 56,
                authentication_type = '',
                cost = 56,
                dead_interval = 56,
                hello_interval = 56,
                interface = 'eth0',
                preamble = '',
                retransmit_interval = 56,
                transmit_delay = 56
            )
        else:
            return OspfConfig(
        )
        """

    def testOspfConfig(self):
        """Test OspfConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
