# coding: utf-8

"""
    IP Address Management API

    The IPAM/DHCP Application is a BloxOne DDI service providing IP address management and DHCP protocol features. The IPAM component provides visibility into and provisioning tools to manage networking spaces, monitoring and reporting of entire IP address infrastructures, and integration with DNS and DHCP protocols. The DHCP component provides DHCP protocol configuration service with on-prem host serving DHCP protocol. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ipam.models.inherited_dhcp_config import InheritedDHCPConfig


class TestInheritedDHCPConfig(unittest.TestCase):
    """InheritedDHCPConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InheritedDHCPConfig:
        """Test InheritedDHCPConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InheritedDHCPConfig`
        """
        model = InheritedDHCPConfig()
        if include_optional:
            return InheritedDHCPConfig(
                abandoned_reclaim_time = ipam.models.inherited_u_int32.InheritedUInt32(
                    action = '', 
                    display_name = '', 
                    source = '', 
                    value = 56, ),
                abandoned_reclaim_time_v6 = ipam.models.inherited_u_int32.InheritedUInt32(
                    action = '', 
                    display_name = '', 
                    source = '', 
                    value = 56, ),
                allow_unknown = ipam.models.inherited_bool.InheritedBool(
                    action = '', 
                    display_name = '', 
                    source = '', 
                    value = True, ),
                allow_unknown_v6 = ipam.models.inherited_bool.InheritedBool(
                    action = '', 
                    display_name = '', 
                    source = '', 
                    value = True, ),
                echo_client_id = ipam.models.inherited_bool.InheritedBool(
                    action = '', 
                    display_name = '', 
                    source = '', 
                    value = True, ),
                filters = ipam.models.filter_list.FilterList(
                    action = '', 
                    display_name = '', 
                    source = '', 
                    value = [
                        ''
                        ], ),
                filters_v6 = ipam.models.filter_list.FilterList(
                    action = '', 
                    display_name = '', 
                    source = '', 
                    value = [
                        ''
                        ], ),
                ignore_client_uid = ipam.models.inherited_bool.InheritedBool(
                    action = '', 
                    display_name = '', 
                    source = '', 
                    value = True, ),
                ignore_list = ipam.models.ignore_item_list.IgnoreItemList(
                    action = '', 
                    display_name = '', 
                    source = '', 
                    value = [
                        ipam.models.ignore_item.IgnoreItem(
                            type = 'client_hex', 
                            value = '01:23:45:67:89:AB', )
                        ], ),
                lease_time = ipam.models.inherited_u_int32.InheritedUInt32(
                    action = '', 
                    display_name = '', 
                    source = '', 
                    value = 56, ),
                lease_time_v6 = ipam.models.inherited_u_int32.InheritedUInt32(
                    action = '', 
                    display_name = '', 
                    source = '', 
                    value = 56, )
            )
        else:
            return InheritedDHCPConfig(
        )
        """

    def testInheritedDHCPConfig(self):
        """Test InheritedDHCPConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
