# coding: utf-8

"""
    DDI Keys API

    The DDI Keys application is a BloxOne DDI service for managing TSIG keys and GSS-TSIG (Kerberos) keys which are used by other BloxOne DDI applications. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from keys.models.generate_tsig_response import GenerateTSIGResponse


class TestGenerateTSIGResponse(unittest.TestCase):
    """GenerateTSIGResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateTSIGResponse:
        """Test GenerateTSIGResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateTSIGResponse`
        """
        model = GenerateTSIGResponse()
        if include_optional:
            return GenerateTSIGResponse(
                result = keys.models.generate_tsig_result.GenerateTSIGResult(
                    secret = '', )
            )
        else:
            return GenerateTSIGResponse(
        )
        """

    def testGenerateTSIGResponse(self):
        """Test GenerateTSIGResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
