# coding: utf-8

"""
    DNS Configuration API

    The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from dns_config.models.auth_nsg import AuthNSG


class TestAuthNSG(unittest.TestCase):
    """AuthNSG unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthNSG:
        """Test AuthNSG
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthNSG`
        """
        model = AuthNSG()
        if include_optional:
            return AuthNSG(
                comment = '',
                external_primaries = [
                    dns_config.models.external_primary.ExternalPrimary(
                        address = '', 
                        fqdn = '', 
                        nsg = '', 
                        protocol_fqdn = '', 
                        tsig_enabled = True, 
                        tsig_key = dns_config.models.tsig_key.TSIGKey(
                            algorithm = '', 
                            comment = '', 
                            key = '', 
                            name = '', 
                            protocol_name = '', 
                            secret = '', ), 
                        type = 'nsg', )
                    ],
                external_secondaries = [
                    dns_config.models.external_secondary.ExternalSecondary(
                        address = '192.0.2.0', 
                        fqdn = 'ns1.example.com', 
                        protocol_fqdn = '', 
                        stealth = True, 
                        tsig_enabled = True, 
                        tsig_key = dns_config.models.tsig_key.TSIGKey(
                            algorithm = '', 
                            comment = '', 
                            key = '', 
                            name = '', 
                            protocol_name = '', 
                            secret = '', ), )
                    ],
                id = '',
                internal_secondaries = [
                    dns_config.models.internal_secondary.InternalSecondary(
                        host = 'dns/host/23311109-fad4-448f-a7a7-55ad791ae7eb', )
                    ],
                name = 'Example Authoritative DNS Server Group',
                nsgs = [
                    ''
                    ],
                tags = None
            )
        else:
            return AuthNSG(
                name = 'Example Authoritative DNS Server Group',
        )
        """

    def testAuthNSG(self):
        """Test AuthNSG"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
