# coding: utf-8

"""
    DNS Configuration API

    The DNS application is a Universal DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured Universal DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from dns_config.api.global_api import GlobalApi

from universal_ddi_client.api_client import ApiClient


class TestGlobalApi(unittest.TestCase):
    """GlobalApi unit test stubs"""

    def setUp(self) -> None:
        api_instance = ApiClient()
        self.api = GlobalApi(api_instance)

    def tearDown(self) -> None:
        pass

    def test_read(self) -> None:
        """Test case for read

        Read the Global configuration object.
        """
        pass

    def test_read2(self) -> None:
        """Test case for read2

        Read the Global configuration object.
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update the Global configuration object.
        """
        pass

    def test_update2(self) -> None:
        """Test case for update2

        Update the Global configuration object.
        """
        pass


if __name__ == '__main__':
    unittest.main()
